#!/usr/bin/env python3
"""
Amalgamate all local headers reachable from an entry point into a single
self-contained header. External includes (system or third-party) are
deduplicated and hoisted to the top.

The single header covers the header-only part of the library: the compile-time
entry point einsum<"ij,jk->ik">(a, b) and the whole runtime lowering. It does
NOT cover einsum::rt::plan(), which parses a subscript that is not known until
run time -- that grammar is compiled into libeinsum_rt and needs the library
linked. einsum/rt/parse.hpp and einsum/util/export.hpp are skipped for that
reason.

Usage:
    python3 scripts/amalgamate.py \
        --entry include/einsum/einsum.hpp \
        --include-dir include \
        --output single_include/einsum.hpp
"""

import argparse
import re
import sys
from pathlib import Path

LOCAL_INCLUDE  = re.compile(r'^\s*#include\s+"([^"]+)"')
SYSTEM_INCLUDE = re.compile(r'^\s*#include\s+(<[^>]+>)')
PRAGMA_ONCE    = re.compile(r'^\s*#pragma\s+once')
INCLUDE_GUARD_IFNDEF = re.compile(r'^\s*#ifndef\s+\S+')
INCLUDE_GUARD_DEFINE = re.compile(r'^\s*#define\s+\S+')
INCLUDE_GUARD_ENDIF  = re.compile(r'^\s*#endif')

# Not part of the header-only library: parse.hpp declares what libeinsum_rt
# defines, and export.hpp only exists to decorate those declarations.
SKIP = {"einsum/rt/parse.hpp", "einsum/util/export.hpp"}


def resolve(path: str, current: Path, include_dir: Path) -> Path | None:
    candidate = (current.parent / path).resolve()
    if candidate.exists():
        return candidate
    candidate = (include_dir / path).resolve()
    if candidate.exists():
        return candidate
    return None


def collect(entry: Path, include_dir: Path,
            visited: list[Path], seen: set[Path],
            system_includes: list[str], seen_system: set[str]) -> None:
    real = entry.resolve()
    if real in seen:
        return
    seen.add(real)

    lines = real.read_text().splitlines()

    # Detect a two-line include-guard pattern and skip those lines
    guard_name: str | None = None
    guard_lines: set[int] = set()

    i = 0
    while i < len(lines):
        # Skip blank lines at the very top before detecting the guard
        stripped = lines[i].strip()
        if not stripped or stripped.startswith("//"):
            i += 1
            continue
        m = INCLUDE_GUARD_IFNDEF.match(lines[i])
        if m:
            guard_name = lines[i].split()[1]
            guard_lines.add(i)
            if i + 1 < len(lines) and INCLUDE_GUARD_DEFINE.match(lines[i + 1]):
                guard_lines.add(i + 1)
        break

    # Mark the final #endif as a guard line (last non-empty line)
    if guard_name is not None:
        for j in range(len(lines) - 1, -1, -1):
            if lines[j].strip():
                if INCLUDE_GUARD_ENDIF.match(lines[j]):
                    guard_lines.add(j)
                break

    body_lines: list[str] = []

    for idx, line in enumerate(lines):
        if idx in guard_lines:
            continue
        if PRAGMA_ONCE.match(line):
            continue

        m_local = LOCAL_INCLUDE.match(line)
        if m_local:
            if m_local.group(1) in SKIP:
                continue
            dep = resolve(m_local.group(1), real, include_dir)
            if dep is None:
                print(f"WARNING: cannot resolve '{m_local.group(1)}' from {real}",
                      file=sys.stderr)
                body_lines.append(line)
            else:
                collect(dep, include_dir, visited, seen, system_includes, seen_system)
            continue

        m_sys = SYSTEM_INCLUDE.match(line)
        if m_sys:
            inc = m_sys.group(1)
            if inc not in seen_system:
                seen_system.add(inc)
                system_includes.append(inc)
            continue

        body_lines.append(line)

    # Strip leading/trailing blank lines from the body
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()

    if body_lines:
        visited.append((real, body_lines))


def amalgamate(entry: Path, include_dir: Path, output: Path,
               guard: str = "EINSUM_SINGLE_INCLUDE_HPP") -> None:
    visited: list[tuple[Path, list[str]]] = []
    seen: set[Path] = set()
    system_includes: list[str] = []
    seen_system: set[str] = set()

    collect(entry, include_dir, visited, seen, system_includes, seen_system)

    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open("w") as f:
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n")
        f.write("// EinsteinSummation, amalgamated -- do not edit manually.\n")
        f.write("// Generated by scripts/amalgamate.py from include/einsum/einsum.hpp.\n")
        f.write("//\n")
        f.write("// This is the header-only library: einsum<\"ij,jk->ik\">(a, b), the Plan\n")
        f.write("// and Bound runtime surface, the views, the lowering and the Eigen\n")
        f.write("// kernels.  It still needs Boost (headers), Eigen and kokkos mdspan on\n")
        f.write("// the include path.\n")
        f.write("//\n")
        f.write("// einsum::rt::plan(), which parses a subscript at run time, is NOT here:\n")
        f.write("// its Boost.Parser grammar is compiled into libeinsum_rt.  Include\n")
        f.write("// <einsum/rt/parse.hpp> and link einsum::rt for that.\n\n")

        for inc in system_includes:
            f.write(f"#include {inc}\n")
        f.write("\n")

        for src, lines in visited:
            f.write(f"// ---- {src.name} ----\n")
            f.write("\n".join(lines))
            f.write("\n\n")

        f.write(f"#endif // {guard}\n")

    print(f"Written {output}  ({output.stat().st_size // 1024} KB, "
          f"{sum(len(l) for _, l in visited)} lines of content)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entry",       default="include/einsum/einsum.hpp")
    parser.add_argument("--include-dir", default="include")
    parser.add_argument("--output",      default="single_include/einsum.hpp")
    parser.add_argument("--guard",       default="EINSUM_SINGLE_INCLUDE_HPP")
    args = parser.parse_args()

    root = Path(__file__).parent.parent
    amalgamate(
        entry       = (root / args.entry).resolve(),
        include_dir = (root / args.include_dir).resolve(),
        output      = (root / args.output).resolve(),
        guard       = args.guard,
    )
