#!/usr/bin/env python3
"""Regenerate the third-party subset an installed einsum ships.

cmake/EinsumVendoredHeaders.cmake is what this writes.  Boost, Eigen and mdspan
are fetched against a pin here and none is a package a machine reliably has, so
an install carries the part of each our public headers actually reach -- found
by asking the compiler for the include closure, not by guessing.

    python3 scripts/vendor_headers.py            # rewrite the list
    python3 scripts/vendor_headers.py --check    # exit 1 if it is stale
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"
GENERATED = ROOT / "cmake" / "EinsumVendoredHeaders.cmake"
DEPENDENCIES = ROOT / "cmake" / "EinsumDependencies.cmake"

# name -> (pin in EinsumDependencies.cmake, unpacked directory, witness file)
DEPS = {
    "boost": (r'EINSUM_BOOST_VERSION\s+"([^"]+)"', "boost-{}", "boost/version.hpp"),
    "eigen": (r'EINSUM_EIGEN_VERSION\s+"([^"]+)"', "eigen-{}", "Eigen/Core"),
    "mdspan": (r'EINSUM_MDSPAN_COMMIT\s+"([^"]+)"', "mdspan-{}/include",
               "experimental/mdspan"),
}

# Every file, every subdirectory, whatever the closure saw.  These are the trees
# whose variant is chosen by a macro rather than by an #include, so the closure
# taken here names the wrong subdirectory for somebody else's build:
#   boost/config       BOOST_COMPILER_CONFIG, the platform and stdlib ladder
#   boost/preprocessor the BOOST_PP_CONFIG_FLAGS() ladder
#   boost/mpl          BOOST_MPL_CFG_COMPILER_DIR
#   Eigen .../arch     the vectorisation backend, which is -march's to choose --
#                      this machine's closure sees SSE, and a consumer building
#                      -march=native on a newer one wants AVX512 to be there
WHOLE = {"boost": ("boost/config", "boost/mpl", "boost/preprocessor"),
         "eigen": ("Eigen/src/Core/arch",)}

# The floor the toolchain probe enforces, in preference order, when $CXX is unset.
COMPILERS = ("g++-15", "g++-14", "clang++-20", "g++", "clang++")

BANNER = """\
# Generated by scripts/vendor_headers.py.  Do not edit.
#
# The third-party directories an installed einsum copies out of the fetched
# sources, one level deep each.  Regenerate after bumping a pin, or after a
# public header names a library it did not before:
#
#     python3 scripts/vendor_headers.py
#
# EinsumInstall.cmake fails the build if a name here holds no files, so a stale
# list is a stopped build rather than a short install.
"""


def closure(cxx: str, roots: dict[str, Path]) -> list[Path]:
    """Every header the installed ones reach, absolute, as the compiler saw it."""
    source = "".join(f'#include "{h.relative_to(INCLUDE).as_posix()}"\n'
                     for h in sorted(INCLUDE.rglob("*.hpp")))
    with tempfile.TemporaryDirectory() as tmp:
        unit = Path(tmp, "installed.cpp")
        unit.write_text(source)
        # -M, not -MM: -MM drops everything found through -isystem, which is
        # every header this is about.
        done = subprocess.run(
            [cxx, "-std=c++23", "-fno-exceptions", "-I", str(INCLUDE),
             *(a for r in roots.values() for a in ("-isystem", str(r))),
             "-M", str(unit)],
            capture_output=True, text=True, check=False)
    if done.returncode:
        sys.exit(f"{cxx} could not preprocess einsum's headers:\n{done.stderr}")
    # Makefile syntax: a target, then paths over backslash-continued lines.
    return [Path(t) for t in done.stdout.replace("\\\n", " ").split()]


def directories(reached: list[Path], name: str, root: Path) -> list[str]:
    """The directories to ship for one dependency, relative to its root."""
    names = {p.parent.relative_to(root).as_posix()
             for p in reached if p.is_absolute() and p.is_relative_to(root)}
    # Named by the files they hold, not by the directories they are: a name
    # holding none installs nothing and trips the check in the CMake.
    names |= {f.parent.relative_to(root).as_posix()
              for lib in WHOLE.get(name, ()) for f in (root / lib).rglob("*")
              if f.is_file()}
    names.discard(".")
    if not names:
        sys.exit(f"the closure reached no {name} headers; that cannot be right")
    # "boost" sorts before "boost/assert": a prefix is shorter than what extends it.
    return sorted(names)


def main() -> int:
    """Rewrite the list, or check it, and report what was found."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--deps", type=Path, default=ROOT / ".deps",
                        help="where the pinned sources were unpacked")
    parser.add_argument("--cxx", default=os.environ.get("CXX"),
                        help="compiler to ask (default: $CXX, else the newest found)")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed list differs, and write nothing")
    args = parser.parse_args()

    pinned = DEPENDENCIES.read_text()
    roots = {}
    for name, (pin, layout, witness) in DEPS.items():
        found = re.search(pin, pinned)
        if found is None:
            sys.exit(f"no pin for {name} in {DEPENDENCIES}")
        root = (args.deps / layout.format(found.group(1))).resolve()
        if not (root / witness).is_file():
            sys.exit(f"no {name} at {root}: it has no {witness}.  Configure once "
                     f"(`cmake --preset release`) to unpack the pins.")
        roots[name] = root

    cxx = args.cxx or next((c for c in COMPILERS if shutil.which(c)), None)
    if cxx is None:
        sys.exit(f"no C++ compiler found; tried $CXX and {', '.join(COMPILERS)}")

    reached = closure(cxx, roots)
    listed = {name: directories(reached, name, root) for name, root in roots.items()}
    wanted = BANNER + "\n".join(
        "set(EINSUM_{}_HEADER_DIRS\n{})\n".format(
            name.upper(), "\n".join(f"        {d}" for d in dirs))
        for name, dirs in listed.items())

    if args.check:
        if not GENERATED.is_file() or GENERATED.read_text() != wanted:
            sys.exit(f"{GENERATED.relative_to(ROOT)} is stale or missing; "
                     f"regenerate it with python3 scripts/vendor_headers.py")
        print(f"{GENERATED.relative_to(ROOT)} is current")
        return 0

    GENERATED.write_text(wanted)
    for name, dirs in listed.items():
        files = sum(len([f for f in (roots[name] / d).glob("*") if f.is_file()])
                    for d in dirs)
        print(f"  {name:7} {len(dirs):4} directories, {files:5} files")
    print(f"{GENERATED.relative_to(ROOT)}: asked {cxx}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
